apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}

subsets:
- addresses:
  - ip: {{ .Values.endpoints.host }}
  ports:
  - name: {{ .Release.Name | quote }}
    port: {{ .Values.endpoints.port }}
    protocol: TCP