apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "traefik-ingress.fullname" . }}
  labels:
    {{- include "traefik-ingress.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http: 
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ .Values.service.name | default "none" }}
            port:
              number: {{ .Values.service.port }}
